export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_PRESCRIPTION_LIST_START = "GET_PRESCRIPTION_LIST_START";
export const GET_PRESCRIPTION_LIST_FAIL = "GET_PRESCRIPTION_LIST_FAIL";
export const GET_PRESCRIPTION_LIST_SUCCESS = "GET_PRESCRIPTION_LIST_SUCCESS";

export const GET_PRESCRIPTION_DETAIL_START = "GET_PRESCRIPTION_DETAIL_START";
export const GET_PRESCRIPTION_DETAIL_FAIL = "GET_PRESCRIPTION_DETAIL_FAIL";
export const GET_PRESCRIPTION_DETAIL_SUCCESS = "GET_PRESCRIPTION_DETAIL_SUCCESS";

export const POST_PRESCRIPTION_DETAIL_START = "POST_PRESCRIPTION_DETAIL_START";
export const POST_PRESCRIPTION_DETAIL_FAIL = "POST_PRESCRIPTION_DETAIL_FAIL";
export const POST_PRESCRIPTION_DETAIL_SUCCESS = "POST_PRESCRIPTION_DETAIL_SUCCESS";