export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_PRESCRIPTION_LIST_START = "GET_PRESCRIPTION_LIST_START";
export const GET_PRESCRIPTION_LIST_FAIL = "GET_PRESCRIPTION_LIST_FAIL";
export const GET_PRESCRIPTION_LIST_SUCCESS = "GET_PRESCRIPTION_LIST_SUCCESS";
