# Generated by Django 2.2.3 on 2019-08-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='direction',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='item_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='release_date',
            field=models.DateField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='title',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
